"""add titulo/fecha_cierre to publication_requests, create destinos_publicacion

Revision ID: 15f24c0ea8ef
Revises: 765173a90970
Create Date: 2026-08-05 16:51:43.884846

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15f24c0ea8ef"
down_revision: str | Sequence[str] | None = "765173a90970"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destinos_publicacion",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("publication_request_id", sa.String(length=36), nullable=False),
        sa.Column("canal", sa.String(length=20), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("wp_post_id", sa.String(), nullable=True),
        sa.Column("wp_url", sa.String(), nullable=True),
        sa.Column("url_publicacion", sa.String(), nullable=True),
        sa.Column("registrado_por_user_id", sa.String(length=36), nullable=True),
        sa.Column("fecha_publicacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_error", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["publication_request_id"],
            ["publication_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["registrado_por_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_destinos_publicacion_publication_request_id"),
        "destinos_publicacion",
        ["publication_request_id"],
        unique=False,
    )
    op.add_column("publication_requests", sa.Column("titulo", sa.String(), nullable=True))
    op.add_column(
        "publication_requests", sa.Column("fecha_cierre", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publication_requests", "fecha_cierre")
    op.drop_column("publication_requests", "titulo")
    op.drop_index(
        op.f("ix_destinos_publicacion_publication_request_id"), table_name="destinos_publicacion"
    )
    op.drop_table("destinos_publicacion")
    # ### end Alembic commands ###
