"""create client, pauta and publication_request tables

Revision ID: 383f7f1f0c15
Revises:
Create Date: 2026-07-30 16:16:30.793583

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "383f7f1f0c15"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("telefono", sa.String(length=30), nullable=False),
        sa.Column("instagram", sa.String(length=100), nullable=True),
        sa.Column("observaciones", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pautas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=False),
        sa.Column("publicaciones_contratadas", sa.Integer(), nullable=False),
        sa.Column("valor_pagado", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("fecha_pago", sa.Date(), nullable=False),
        sa.Column("observaciones", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pautas_client_id"), "pautas", ["client_id"], unique=False)
    op.create_table(
        "publication_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pauta_id", sa.String(length=36), nullable=True),
        sa.Column("fecha_recepcion", sa.DateTime(timezone=True), nullable=False),
        sa.Column("texto", sa.String(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("prioridad_manual", sa.Boolean(), nullable=False),
        sa.Column("observaciones", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pauta_id"],
            ["pautas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_publication_requests_pauta_id"), "publication_requests", ["pauta_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_publication_requests_pauta_id"), table_name="publication_requests")
    op.drop_table("publication_requests")
    op.drop_index(op.f("ix_pautas_client_id"), table_name="pautas")
    op.drop_table("pautas")
    op.drop_table("clients")
    # ### end Alembic commands ###
