"""create gastos table

Revision ID: 4657d2234272
Revises: f603d84b0c98
Create Date: 2026-08-14 17:40:07.130518

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4657d2234272"
down_revision: str | Sequence[str] | None = "f603d84b0c98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gastos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=False),
        sa.Column("valor", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("fecha_registro", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gastos_fecha"), "gastos", ["fecha"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gastos_fecha"), table_name="gastos")
    op.drop_table("gastos")
    # ### end Alembic commands ###
