"""create media_assets table

Revision ID: f603d84b0c98
Revises: a1b2c3d4e5f6
Create Date: 2026-08-07 00:28:10.354694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f603d84b0c98"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("publication_request_id", sa.String(length=36), nullable=False),
        sa.Column("tipo", sa.String(length=10), nullable=False),
        sa.Column("nombre_archivo", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("tamano_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("fecha_subida", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subido_por_user_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["publication_request_id"],
            ["publication_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subido_por_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_media_assets_publication_request_id"),
        "media_assets",
        ["publication_request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_assets_publication_request_id"), table_name="media_assets")
    op.drop_table("media_assets")
    # ### end Alembic commands ###
